import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const REPO_OWNER = 'hdparks';
const REPO_NAME = 'flex';
const BASE_BRANCH = 'main';

function getHeaders() {
  return {
    Authorization: `Bearer ${GITHUB_TOKEN}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };
}

export async function getCurrentBranch() {
  const { stdout } = await execAsync('git branch --show-current');
  return stdout.trim();
}

export async function getChangedFiles() {
  const { stdout } = await execAsync('git diff --name-only HEAD');
  return stdout.split('\n').filter(Boolean);
}

export async function getStagedFiles() {
  const { stdout } = await execAsync('git diff --name-only --cached');
  return stdout.split('\n').filter(Boolean);
}

export async function hasChanges() {
  const { stdout } = await execAsync('git status --porcelain');
  return stdout.trim().length > 0;
}

export async function stageAllChanges() {
  await execAsync('git add -A');
}

export async function createCommit(message) {
  await execAsync(`git commit -m "${message.replace(/"/g, '\\"')}"`);
}

export async function createBranch(branchName) {
  try {
    await execAsync(`git checkout -b ${branchName}`);
  } catch (err) {
    if (err.message.includes('already exists')) {
      await execAsync(`git checkout ${branchName}`);
    } else {
      throw err;
    }
  }
}

export async function pushBranch(branchName) {
  await execAsync(`git push -u origin ${branchName} --force`);
}

export async function checkoutBranch(branchName) {
  await execAsync(`git checkout ${branchName}`);
}

export async function checkoutMain() {
  await execAsync(`git checkout ${BASE_BRANCH}`);
  await execAsync('git pull origin ' + BASE_BRANCH);
}

export async function createPullRequest(options) {
  const { title, body, head, base = BASE_BRANCH } = options;

  const response = await fetch(
    `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls`,
    {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({
        title,
        body,
        head,
        base,
      }),
    }
  );

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`Failed to create PR: ${error.message}`);
  }

  return response.json();
}

export async function addLabelToIssue(issueNumber, labels) {
  const response = await fetch(
    `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues/${issueNumber}/labels`,
    {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({ labels }),
    }
  );

  if (!response.ok) {
    const error = await response.json();
    console.error('Failed to add labels:', error.message);
  }

  return response.json();
}

export async function getRepoInfo() {
  const response = await fetch(
    `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}`,
    {
      method: 'GET',
      headers: getHeaders(),
    }
  );

  if (!response.ok) {
    throw new Error('Failed to get repo info');
  }

  return response.json();
}

export async function branchExists(branchName) {
  try {
    await execAsync(`git rev-parse --verify ${branchName}`);
    return true;
  } catch {
    return false;
  }
}

export async function deleteBranch(branchName) {
  try {
    await execAsync(`git branch -D ${branchName}`);
  } catch (err) {
    console.warn('Could not delete local branch:', err.message);
  }
}

export async function resetToMain() {
  await checkoutMain();
  const status = await hasChanges();
  if (status) {
    await execAsync('git checkout -- .');
    await execAsync('git clean -fd');
  }
}

export async function getCommitDiff() {
  const { stdout } = await execAsync('git diff HEAD~1 HEAD --stat');
  return stdout;
}

export async function createBugFixPR(bugId, description, severity) {
  const branchName = `fix/bug-${bugId.slice(0, 8)}`;

  console.log('[GitHub] Creating branch:', branchName);

  await checkoutMain();
  await createBranch(branchName);

  const hasUncommitted = await hasChanges();
  if (!hasUncommitted) {
    console.log('[GitHub] No changes to commit');
    await deleteBranch(branchName);
    return null;
  }

  await stageAllChanges();
  await createCommit(`fix: resolve bug ${bugId.slice(0, 8)} - ${severity}`);

  console.log('[GitHub] Pushing branch...');
  await pushBranch(branchName);

  console.log('[GitHub] Creating PR...');
  const pr = await createPullRequest({
    title: `[Bug Fix] ${severity}: ${description.slice(0, 50)}...`,
    body: `## Bug Report ID
${bugId}

## Severity
${severity}

## Description
${description}

## Changes
This PR addresses the reported bug. Please review carefully.

---
*Auto-generated by Flex bug processor*`,
    head: branchName,
  });

  console.log('[GitHub] PR created:', pr.html_url);
  return pr;
}